Fixed tests for ComponentLookupError and Decimal.
Traceback is slightly different than we expect on Plone 5.2:

```
File "/Users/maurits/community/plone-coredev/5.2/src/plone.tiles/plone/tiles/tests/../data.rst", line 112, in data.rst
Failed example:
    encode(data, IUnsupported) # doctest: +ELLIPSIS
Expected:
    Traceback (most recent call last):
    ...
    zope.interface.interfaces.ComponentLookupError: Cannot URL encode decimal of type <class 'zope.schema._field.Decimal'>
Got:
    Traceback (most recent call last):
      File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest data.rst[24]>", line 1, in <module>
        encode(data, IUnsupported) # doctest: +ELLIPSIS
      File "/Users/maurits/community/plone-coredev/5.2/src/plone.tiles/plone/tiles/data.py", line 285, in encode
        field.__class__
    ComponentLookupError: Cannot URL encode decimal of type <class 'zope.schema._bootstrapfields.Decimal'>
```

But for other versions it may be the same as always, so make the test less strict.